services:
  postgres:
    image: postgres:16
    container_name: skynet_postgres
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
      POSTGRES_DB: skinet
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: skynet_redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
  